name: deploy-pipeline

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    name: deploy-pipeline 
    runs-on: ubuntu-latest
    env:
      HOPSWORKS_HOST: "2a5f8040-2d0d-11ed-b5c5-c151c2fe58c1.cloud.hopsworks.ai"
      HOPSWORKS_PROJECT: "cicd_blog"
      HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Hopsworks library
        run: pip install git+https://github.com/logicalclocks/hopsworks-api@main#egg=hopsworks&subdirectory=python wheel

      - name: Build project wheel
        run: python setup.py bdist_wheel

      - name: Pull changes
        run: python utils/pull.py

      - name: Configure Environment
        run: |
          python utils/pip.py \
            --requirements-path Resources/hopsworks-gh-example/requirements.txt \
            --wheel-local-path dist/fraud-1-py3-none-any.whl \
            --wheel-hopsworks-path Resources/

      - name: Deploy transaction jobs
        run: |
          python utils/job.py \
            --name transactions \
            --path fraud/features/transactions/job_conf.json \
            --hopsworks-path Resources/hopsworks-gh-example/fraud/features/transactions/transactions.py

      - name: Deploy profiles jobs
        run: |
          python utils/job.py \
            --name profiles \
            --path fraud/features/profiles/job_conf.json \
            --hopsworks-path Resources/hopsworks-gh-example/fraud/features/profiles/profiles.py

      - name: Deploy US fraud model training job
        run: |
          python utils/job.py \
            --name fraud_model_us \
            --path fraud/model/fraud_us/job_conf.json \
            --hopsworks-path Resources/hopsworks-gh-example/fraud/model/fraud_us/model.py
